# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookeep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(to='Bookeep.UserProfile'),
        ),
    ]
