# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookeep', '0002_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
