# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookeep', '0004_book_time_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time_read',
            field=models.DurationField(),
        ),
    ]
